# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stereo_vehicle.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'stereo_vehicle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14stereo_vehicle.proto\x12\x0estereo_vehicle\"\x8d\x01\n\rHeightRequest\x12\x12\n\nleft_image\x18\x01 \x01(\x0c\x12\x13\n\x0bright_image\x18\x02 \x01(\x0c\x12\t\n\x01x\x18\x03 \x01(\x05\x12\t\n\x01y\x18\x04 \x01(\x05\x12\x14\n\x0c\x66ocal_length\x18\x05 \x01(\x02\x12\x10\n\x08\x62\x61seline\x18\x06 \x01(\x02\x12\x15\n\rcamera_height\x18\x07 \x01(\x02\"6\n\x16IdentifyVehicleRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05video\x18\x02 \x01(\x0c\" \n\x0eNumberResponse\x12\x0e\n\x06number\x18\x01 \x01(\x02\"\'\n\x14\x42ooleanArrayResponse\x12\x0f\n\x07results\x18\x01 \x03(\x08\x32\xbf\x01\n\x0fImageProcessing\x12K\n\nFindHeight\x12\x1d.stereo_vehicle.HeightRequest\x1a\x1e.stereo_vehicle.NumberResponse\x12_\n\x0fIdentifyVehicle\x12&.stereo_vehicle.IdentifyVehicleRequest\x1a$.stereo_vehicle.BooleanArrayResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stereo_vehicle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEIGHTREQUEST']._serialized_start=41
  _globals['_HEIGHTREQUEST']._serialized_end=182
  _globals['_IDENTIFYVEHICLEREQUEST']._serialized_start=184
  _globals['_IDENTIFYVEHICLEREQUEST']._serialized_end=238
  _globals['_NUMBERRESPONSE']._serialized_start=240
  _globals['_NUMBERRESPONSE']._serialized_end=272
  _globals['_BOOLEANARRAYRESPONSE']._serialized_start=274
  _globals['_BOOLEANARRAYRESPONSE']._serialized_end=313
  _globals['_IMAGEPROCESSING']._serialized_start=316
  _globals['_IMAGEPROCESSING']._serialized_end=507
# @@protoc_insertion_point(module_scope)
