# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto2.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cproto2.proto\x12\x11stabilized_images\"\x07\n\x05\x45mpty\"\x1e\n\rFrameResponse\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x32\x61\n\rImageReceiver\x12P\n\x12GetStabilizedFrame\x12\x18.stabilized_images.Empty\x1a .stabilized_images.FrameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_FRAMERESPONSE']._serialized_start=44
  _globals['_FRAMERESPONSE']._serialized_end=74
  _globals['_IMAGERECEIVER']._serialized_start=76
  _globals['_IMAGERECEIVER']._serialized_end=173
# @@protoc_insertion_point(module_scope)
